* Repository
Official Repository: https://github.com/KoalaGroup/KoalaSoft
Official Repository(mirror): https://pandaatfair.githost.io/KoalaGroup/KoalaSoft

Configure git to push to multiple remotes simultaneously:
#+BEGIN_SRC sh
git remote set-url --add --push origin https://github.com/KoalaGroup/KoalaSoft
git remote set-url --add --push origin https://pandaatfair.githost.io/KoalaGroup/KoalaSoft
#+END_SRC

* Install

** FairSoft
Official Repository: https://github.com/FairRootGroup/FairSoft
Installation is based on the guide on the official github repository.
*** Dependencies
Check the DEPENDECY file in the repository.
Use OS's package manager to install external dependencies.

*** FairSoft
    1. checkout the desired branch/tag:
    #+BEGIN_SRC sh
    git tag
    git checkout -b desired_tag desired_tag
    #+END_SRC
    2. mkdir a new installation directory out of the src directory
    3. change to the src directory, and run /configure.sh/
    4. Set up the /SIMPATH/ environment variable to the install directory of FairSoft
    
** FairRoot
Official Repository: https://github.com/FairRootGroup/FairRoot

   1. make sure /SIMPATH/ is correctly set, which should point to FairSoft installation directory
   2. mkdir a new installation directory out of the src directory
   3. clone the repository and checkout the desired branch/tag
    #+BEGIN_SRC sh
    git tag
    git checkout -b desired_tag desired_tag
    #+END_SRC
   4. mkdir a new build directory
   5. change to build directory[fn:1]
    #+BEGIN_SRC sh
    cmake -DCMAKE_INSTALL_PREFIX=install_dir ..
    #+END_SRC
   6. make && make install
   7. set up the /FAIRROOTPATH/ environment variable to the install directory of FairRoot


** KoalaSoft
   1. make sure both /SIMPATH/ and /FAIRROOTPATH/ have been setup correctly
   2. clone the KoalaSoft repository
   3. enter into source directory
   4. enter build directory:
      #+BEGIN_SRC sh
      cmake ..
      make -j8
      #+END_SRC
   5. source /config.h/ under build directory before running any macros 

** Running
   All simulation are based on ROOT macros. These macros are stored under /macro/ directory. 
   Right now, two macros are provided:
   1. /run_sim.C/ will generate events covering the 4pi angle
   2. /run_sim_filtered.C/ will add a event filter before passing the generated event to the geant engine.
   Only events within the Recoil detector range will be simulated.

** Version recommendation
   Both FairSoft and FairRoot are built upon ROOT, Geant4 and the build tool cmake. 
   These packages are under active development, thus resulting in frequent version update in FairSoft and FairRoot.
   More critically, the newest versions of FairSoft and FairRoot may not be compatible with projects based on old version.
   KoalaSoft is no exception. Keeping update with the latest FairSoft and FairRoot is a big burden.
   Normally, specific version of FairSoft and FairRoot will be tested and recommended for KoalaSoft installation.

   Currently, FairSoft *oct17p1* and FairRoot *v-17.10c* are tested and recommended.

* Footnotes

[fn:1] Some version of FairRoot may require specific version of cmake, which the OS may not have installed. In this case, normally, you can use the version of cmake installed by FairSoft.
       This practice also applies to project codes based on FairRoot.
